// <auto-generated />
namespace Negocio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Incluindo_Nova_Propriedade_no_Item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Incluindo_Nova_Propriedade_no_Item));
        
        string IMigrationMetadata.Id
        {
            get { return "202001261650461_Incluindo_Nova_Propriedade_no_Item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
